package com.example.Zan.nrfuart;

import android.graphics.Color;

import java.util.ArrayList;
import java.util.List;

import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;

/**
 * Created by nodgd on 2017/09/16.
 */

class MonitorCardData {

    private String title = null;
    private int id = 0;
    private List<Integer> messageFlow = null;
    private int Channel;

    public void setChannel(int channel) {
        Channel = channel;
    }

    public int getChannel() {
        return Channel;
    }


    public boolean checkchannel(int channel) {
        return (Channel == channel);
    }


    public void setTitle(String title) {
        this.title = title;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setMessageFlow(int[] msg) {
        messageFlow = new ArrayList<>();
        for (int i = 0; i < msg.length; i++) {
            messageFlow.add(msg[i]);
        }
    }

    public void setMessageFlow(List<Integer> msg) {
        messageFlow = msg;
    }

    public void add(int msgItem) {
        messageFlow.add(msgItem);
    }

    public void add(int[] msg) {
        for (int msgItem : msg) {
            messageFlow.add(msgItem);
        }
    }

    public void add(List<Integer> msg) {
        for (Integer msgItem : msg) {
            messageFlow.add(msgItem);
        }
    }

    public String getTitle() {
        if (title == null || title.equals("")) {
            return "Monitor Card Title";
        }
        return title;
    }

    public String getIdInString() {
        return "" + id;
    }

    public LineChartData getLineChartData() {
        //流数据变成点序列
        List<PointValue> valueList = new ArrayList<>();
        if (messageFlow != null) {
            for (int i = 0; i < messageFlow.size(); i++) {
                valueList.add(new PointValue(i, messageFlow.get(i)));
            }
        }
        //点序列变成线
        Line line = new Line(valueList);
        line.setColor(Color.BLUE);
        line.setCubic(false);
        line.setFilled(false);
        line.setHasPoints(false);
        line.setStrokeWidth(1);
        //线变成线序列，但是线序列里面只有一条线
        List<Line> lineList = new ArrayList<>();
        lineList.add(line);

        //x轴
        Axis axisX = new Axis();
        axisX.setTextColor(Color.RED);
        axisX.setTextSize(10);
        axisX.setAutoGenerated(true);

        //y轴
        Axis axisY = new Axis();
        axisY.setTextColor(Color.RED);
        axisY.setTextSize(10);
        axisY.setAutoGenerated(true);

        //新建一个可以传入的数据，填入数据
        LineChartData lineChartData = new LineChartData();
        lineChartData.setLines(lineList);
        lineChartData.setAxisXBottom(axisX);
        lineChartData.setAxisYLeft(axisY);
        return lineChartData;
    }
}
